
package br.edu.ifpr.bsi.sispat.view;

/**
 *
 * @author jaque
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLBUsuario = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jBTLogoff = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        telaFundo = new javax.swing.JDesktopPane();
        jLBFundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMCadastros = new javax.swing.JMenu();
        jMDepartamento = new javax.swing.JMenu();
        jMDepCadastro = new javax.swing.JMenuItem();
        jMDepConsulta = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMPatriCadastro = new javax.swing.JMenuItem();
        jMPatriConsulta = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMFuncCadastro = new javax.swing.JMenuItem();
        jMFuncConsulta = new javax.swing.JMenuItem();
        jMRelatorios = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMSeguranca = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMFerramentas = new javax.swing.JMenu();
        jMTelaFundo = new javax.swing.JMenu();
        jMAddImagem = new javax.swing.JMenuItem();
        jMRemoverImagem = new javax.swing.JMenuItem();
        jMRestaurarImagem = new javax.swing.JMenuItem();
        jMSobreSistema = new javax.swing.JMenuItem();
        jMSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CP - Tela Principal");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifpr/bsi/sispat/imagens/Logo.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setText("Horário do sistema");

        jLabel4.setText("Usuário:");

        jLBUsuario.setText("Nome");

        jLabel5.setText("Cargo:");

        jLabel8.setText("texto");

        jLabel6.setText("G. Acesso:");

        jLabel9.setText("texto");

        jBTLogoff.setBackground(new java.awt.Color(153, 153, 255));
        jBTLogoff.setText("Logoff");
        jBTLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTLogoffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLBUsuario)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(63, 63, 63))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(74, 74, 74))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jBTLogoff, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLBUsuario))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addGap(28, 28, 28)
                .addComponent(jBTLogoff)
                .addGap(32, 32, 32)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 138, Short.MAX_VALUE))
        );

        jLabel1.setText("Controle Patrimonial Projeto CP - Sistema desenvolvido por Jaqueline Gabriele Dias - Todos os direitos reservados");

        jLBFundo.setText("jLabel7");

        telaFundo.setLayer(jLBFundo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout telaFundoLayout = new javax.swing.GroupLayout(telaFundo);
        telaFundo.setLayout(telaFundoLayout);
        telaFundoLayout.setHorizontalGroup(
            telaFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLBFundo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        telaFundoLayout.setVerticalGroup(
            telaFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaFundoLayout.createSequentialGroup()
                .addComponent(jLBFundo)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMCadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifpr/bsi/sispat/icones/registro.png"))); // NOI18N
        jMCadastros.setText("Cadastros  |");

        jMDepartamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifpr/bsi/sispat/icones/departamento.png"))); // NOI18N
        jMDepartamento.setText("Departamentos");

        jMDepCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifpr/bsi/sispat/icones/mais.png"))); // NOI18N
        jMDepCadastro.setText("Cadastrar");
        jMDepartamento.add(jMDepCadastro);

        jMDepConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifpr/bsi/sispat/icones/pesquisa.png"))); // NOI18N
        jMDepConsulta.setText("Consultar");
        jMDepartamento.add(jMDepConsulta);

        jMCadastros.add(jMDepartamento);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifpr/bsi/sispat/icones/patrimonios.png"))); // NOI18N
        jMenu7.setText("Patrimônios");

        jMPatriCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifpr/bsi/sispat/icones/mais.png"))); // NOI18N
        jMPatriCadastro.setText("Cadastrar");
        jMenu7.add(jMPatriCadastro);

        jMPatriConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifpr/bsi/sispat/icones/pesquisa.png"))); // NOI18N
        jMPatriConsulta.setText("Consultar");
        jMPatriConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMPatriConsultaActionPerformed(evt);
            }
        });
        jMenu7.add(jMPatriConsulta);

        jMCadastros.add(jMenu7);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifpr/bsi/sispat/icones/funcionario.png"))); // NOI18N
        jMenu8.setText("Funcionário");

        jMFuncCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifpr/bsi/sispat/icones/mais.png"))); // NOI18N
        jMFuncCadastro.setText("Cadastrar");
        jMenu8.add(jMFuncCadastro);

        jMFuncConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifpr/bsi/sispat/icones/pesquisa.png"))); // NOI18N
        jMFuncConsulta.setText("Consultar");
        jMenu8.add(jMFuncConsulta);

        jMCadastros.add(jMenu8);

        jMenuBar1.add(jMCadastros);

        jMRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifpr/bsi/sispat/icones/relatorio.png"))); // NOI18N
        jMRelatorios.setText("Relatórios   |");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifpr/bsi/sispat/icones/departamento.png"))); // NOI18N
        jMenuItem1.setText("Departamentos");
        jMRelatorios.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifpr/bsi/sispat/icones/funcionario.png"))); // NOI18N
        jMenuItem2.setText("Funcionários");
        jMRelatorios.add(jMenuItem2);

        jMenuItem3.setText("Patrimônios");
        jMRelatorios.add(jMenuItem3);

        jMenuBar1.add(jMRelatorios);

        jMSeguranca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifpr/bsi/sispat/icones/trancar.png"))); // NOI18N
        jMSeguranca.setText("Segurança   |");

        jMenuItem4.setText("Fazer backup");
        jMSeguranca.add(jMenuItem4);

        jMenuItem5.setText("Restaurar backup");
        jMSeguranca.add(jMenuItem5);

        jMenuBar1.add(jMSeguranca);

        jMFerramentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifpr/bsi/sispat/icones/processo.png"))); // NOI18N
        jMFerramentas.setText("Ferramentas   |");

        jMTelaFundo.setText("Tela de fundo");

        jMAddImagem.setText("Add imagem");
        jMTelaFundo.add(jMAddImagem);

        jMRemoverImagem.setText("Remover imagem");
        jMTelaFundo.add(jMRemoverImagem);

        jMRestaurarImagem.setText("Restaurar padrão");
        jMTelaFundo.add(jMRestaurarImagem);

        jMFerramentas.add(jMTelaFundo);

        jMSobreSistema.setText("Sobre o sistema");
        jMFerramentas.add(jMSobreSistema);

        jMenuBar1.add(jMFerramentas);

        jMSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifpr/bsi/sispat/icones/sair.png"))); // NOI18N
        jMSair.setText("Sair");
        jMSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(telaFundo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator5)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(234, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(238, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addComponent(telaFundo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMPatriConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMPatriConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMPatriConsultaActionPerformed

    private void jBTLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTLogoffActionPerformed
        // TODO add your handling code here:
        
        Teste tela = new Teste();
        telaFundo.add(tela);
        tela.setVisible(true);
        
    }//GEN-LAST:event_jBTLogoffActionPerformed

    private void jMSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMSairMouseClicked
        // TODO add your handling code here:
        Teste2 tela = new Teste2();
        telaFundo.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_jMSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTLogoff;
    private javax.swing.JLabel jLBFundo;
    private javax.swing.JLabel jLBUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMAddImagem;
    private javax.swing.JMenu jMCadastros;
    private javax.swing.JMenuItem jMDepCadastro;
    private javax.swing.JMenuItem jMDepConsulta;
    private javax.swing.JMenu jMDepartamento;
    private javax.swing.JMenu jMFerramentas;
    private javax.swing.JMenuItem jMFuncCadastro;
    private javax.swing.JMenuItem jMFuncConsulta;
    private javax.swing.JMenuItem jMPatriCadastro;
    private javax.swing.JMenuItem jMPatriConsulta;
    private javax.swing.JMenu jMRelatorios;
    private javax.swing.JMenuItem jMRemoverImagem;
    private javax.swing.JMenuItem jMRestaurarImagem;
    private javax.swing.JMenu jMSair;
    private javax.swing.JMenu jMSeguranca;
    private javax.swing.JMenuItem jMSobreSistema;
    private javax.swing.JMenu jMTelaFundo;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JDesktopPane telaFundo;
    // End of variables declaration//GEN-END:variables
}
